kits:
    starter: default
    default:
        items:
        - 278 1 dig_speed:2 name:13_test
        - 279 1 dig_speed:2 name:2
        - 277 1 dig_speed:3 name:3
        - 284 1 durability:3 name:4
        - book book
msg:
    kitsuccsess: '&eÞér hefur verið fært kittið: {kit}'
    kiterror: '&cÞetta kit er ekki til!'