name: SandkasinnKits
author: TheNokar
version: 0.1
softdepend: [Essentials]
main: net.Plommer.SandkassinnKits.SandkassinnKits
commands:
    kits:
        description: Kits commands
        aliases: [kit]